import { DeviceProfile, LayoutGlitchItem } from '../types';

export const EMULATOR_DEVICES: DeviceProfile[] = [
  // Mobile Devices
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    category: 'mobile',
    width: 393,
    height: 852,
    dpr: 3,
    aspectRatio: '19.5:9',
    os: 'ios',
    bezelRadius: 48,
  },
  {
    id: 'pixel-8',
    name: 'Google Pixel 8',
    category: 'mobile',
    width: 412,
    height: 915,
    dpr: 2.6,
    aspectRatio: '20:9',
    os: 'android',
    bezelRadius: 40,
  },
  {
    id: 'galaxy-s24',
    name: 'Samsung Galaxy S24',
    category: 'mobile',
    width: 360,
    height: 780,
    dpr: 3,
    aspectRatio: '19.5:9',
    os: 'android',
    bezelRadius: 36,
  },
  {
    id: 'iphone-se',
    name: 'iPhone SE (Compact)',
    category: 'mobile',
    width: 375,
    height: 667,
    dpr: 2,
    aspectRatio: '16:9',
    os: 'ios',
    bezelRadius: 24,
  },

  // Tablet Devices
  {
    id: 'ipad-air',
    name: 'iPad Air (10.9")',
    category: 'tablet',
    width: 820,
    height: 1180,
    dpr: 2,
    aspectRatio: '4:3',
    os: 'ios',
    bezelRadius: 28,
  },
  {
    id: 'ipad-pro-11',
    name: 'iPad Pro 11"',
    category: 'tablet',
    width: 834,
    height: 1194,
    dpr: 2,
    aspectRatio: '1.43:1',
    os: 'ios',
    bezelRadius: 28,
  },
  {
    id: 'galaxy-tab-s9',
    name: 'Galaxy Tab S9',
    category: 'tablet',
    width: 800,
    height: 1280,
    dpr: 2,
    aspectRatio: '16:10',
    os: 'android',
    bezelRadius: 24,
  },

  // Desktop & Laptop
  {
    id: 'macbook-pro-14',
    name: 'MacBook Pro 14"',
    category: 'desktop',
    width: 1280,
    height: 800,
    dpr: 2,
    aspectRatio: '16:10',
    os: 'macos',
    bezelRadius: 18,
  },
  {
    id: 'desktop-hd',
    name: 'Full HD Monitor',
    category: 'desktop',
    width: 1440,
    height: 900,
    dpr: 1,
    aspectRatio: '16:10',
    os: 'windows',
    bezelRadius: 12,
  },
];

export const LAYOUT_GLITCH_AUDIT_REPORT: LayoutGlitchItem[] = [
  {
    id: 'glitch-1',
    title: 'Storage & Action Card Overflow on Mobile Portrait',
    viewport: 'Mobile Portrait (360px - 393px)',
    aspectRatio: '19.5:9 / 20:9',
    category: 'overflow',
    severity: 'high',
    glitchDescription: 'Multi-column metric stat tiles and quick action buttons forced horizontal clipping and triggered a 14px horizontal scrollbar on viewport widths under 390px.',
    rootCause: 'Fixed column grid classes (grid-cols-4) without mobile-first responsive breakpoints or min-w-0 truncation boundaries.',
    fixApplied: 'Refactored to dynamic responsive grid: grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 with min-w-0 on text containers and strict w-full boundary.',
    status: 'verified',
  },
  {
    id: 'glitch-2',
    title: 'Table Header & Modified Date Column Clipping',
    viewport: 'Mobile Portrait & Small Tablet (375px - 768px)',
    aspectRatio: '16:9 & 4:3 Portrait',
    category: 'alignment',
    severity: 'high',
    glitchDescription: 'File list table displayed 5 columns (Name, Size, Modified Date, Sync Status, Actions) simultaneously, squeezing action buttons off-screen.',
    rootCause: 'Lack of selective column hiding for small screens and missing horizontal scroll container wrapper.',
    fixApplied: 'Implemented mobile card view toggle + responsive column visibility hiding secondary metadata on small viewports and adding smooth swipeable table containers.',
    status: 'verified',
  },
  {
    id: 'glitch-3',
    title: 'Modal & Vault Key Entry Truncation in Mobile Landscape',
    viewport: 'Mobile Landscape (Height: 393px - 412px)',
    aspectRatio: '19.5:9 Landscape',
    category: 'overflow',
    severity: 'high',
    glitchDescription: 'In landscape mobile orientations (e.g. 852×393 or 780×360), dialog headers, password inputs, and action buttons exceeded vertical viewport height, hiding the submit button behind the bottom edge.',
    rootCause: 'Modal containers had fixed heights or lacked max-h-[85vh] with internal overflow-y-auto scrolling.',
    fixApplied: 'Enforced max-h-[90dvh] overflow-y-auto on all modals, popovers, and drawers with compact header paddings for short viewports.',
    status: 'verified',
  },
  {
    id: 'glitch-4',
    title: 'Touch Target Accessibility Deficit (< 44px)',
    viewport: 'All Mobile & Touch Screen Viewports',
    aspectRatio: 'All',
    category: 'touch_target',
    severity: 'medium',
    glitchDescription: 'File action icon buttons (delete, share, star, offline pin) measured 28×28px, failing WCAG 2.2 touch target criterion of 44×44px.',
    rootCause: 'Buttons used p-1 or p-1.5 sizing without minimum touch bounding boxes.',
    fixApplied: 'Upgraded all icon buttons to min-h-[44px] min-w-[44px] or flex center touch padding shells with active visual press feedback.',
    status: 'verified',
  },
  {
    id: 'glitch-5',
    title: 'Image Aspect Ratio Distortion on Tablet Transitions',
    viewport: 'Tablet Portrait to Landscape (820px <-> 1180px)',
    aspectRatio: '4:3 & 16:10',
    category: 'image_scaling',
    severity: 'medium',
    glitchDescription: 'Image gallery previews and thumbnail cards stretched non-proportionally when rotating from portrait (820px) to landscape (1180px).',
    rootCause: 'Images lacked aspect-ratio CSS constraints and object-cover rules.',
    fixApplied: 'Wrapped all preview images in aspect-video or aspect-[4/3] containers with object-cover and dynamic srcset DPR crisp rendering.',
    status: 'verified',
  },
  {
    id: 'glitch-6',
    title: 'Header Navigation Wrap & Search Bar Collision',
    viewport: 'Tablet Portrait (768px - 834px)',
    aspectRatio: '4:3 & 1.43:1',
    category: 'alignment',
    severity: 'medium',
    glitchDescription: 'Header bar containing logo, global search input, sync status badge, and user profile collapsed awkwardly into 3 rows, occluding tab navigation.',
    rootCause: 'Header lacked responsive flex-wrap logic and adaptive collapsible search toggle for tablet widths.',
    fixApplied: 'Streamlined header layout with responsive collapsing search trigger on tablet portrait and clean flex-wrap alignment.',
    status: 'verified',
  },
];
